import { Model, TransactionToSave } from "./deposit-monitor-manager";
import { AddressIdentityDelegate, BaseAddress, MonitorDao, TransactionDao } from "./types";
import { Modeler } from "vineyard-ground/source/modeler";
import { Collection } from "vineyard-ground/source/collection";
import { blockchain } from "vineyard-blockchain";
export declare function listPendingSingleCurrencyTransactions(ground: Modeler, maxBlockIndex: number): Promise<blockchain.SingleTransaction[]>;
export declare function saveSingleCurrencyBlock(blockCollection: Collection<blockchain.Block>, block: blockchain.Block): Promise<blockchain.Block>;
export declare function getTransactionByTxid(transactionCollection: Collection<blockchain.SingleTransaction>, txid: string): Promise<blockchain.SingleTransaction | undefined>;
export declare function getOrCreateAddressReturningId<Identity>(addressCollection: Collection<BaseAddress<Identity>>, externalAddress: string): Promise<Identity>;
export declare function saveSingleCurrencyTransaction<AddressIdentity, BlockIdentity>(transactionCollection: Collection<blockchain.SingleTransaction>, getOrCreateAddress: AddressIdentityDelegate<AddressIdentity>, transaction: TransactionToSave): Promise<blockchain.SingleTransaction>;
export declare function createSingleCurrencyTransactionDao(model: Model): TransactionDao;
export declare function createEthereumExplorerDao(model: Model): MonitorDao;
export declare function scanEthereumExplorerBlocks(dao: MonitorDao, client: blockchain.ReadClient<blockchain.SingleTransaction>): any;
